server:
    port: 9002
spring:
    application:
        name: gateway-server

    cloud:
        config:
            discovery:
                enabled: true
                service-id: config-server
            profile: dev
            label: main
        bus:
            enabled: true
        gateway:
            # 路由集合
            routes:
                - id: demo-server #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
                  uri: lb://demo-server #匹配后提供服务的路由地址
                  predicates:
                      - Path=/v1/** # 断言，路径相匹配的进行路由

    config:
        import: "optional:configserver:"
    main:
        web-application-type: reactive
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/

#spring:
#  cloud:
#    stream:
#      default-binder: rabbit
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
management:
    endpoints:
        web:
            exposure:
                include: "bus-refresh"
