# Gateway 服务的配置示例
server:
  port: 9002

spring:
  application:
    name: gateway-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: demo-service-route
          uri: lb://demo-service  # 转发到 demo-service，lb:// 表示使用负载均衡器
          predicates:
            - Path=/v1/**  # 匹配 /v1/ 开头的所有请求
